<?php

return \StubsGenerator\Finder::create()
	->in(
		[
			'vendor/the-events-calendar/the-events-calendar/vendor',
			'vendor/the-events-calendar/the-events-calendar/src',
		]
	)
	->notPath(
		[
			'Events/Integrations',
			'Tribe/Event_Status/Compatibility/Filter_Bar/Events_Status_Filter.php',
			'woocommerce/action-scheduler',
		]
	)
	->append(
		\StubsGenerator\Finder::create()
			->in(
				[
					'vendor/the-events-calendar/the-events-calendar/common',
				]
			)
			->notPath(
				[
					'src/Tribe/Debug_Bar',
				]
			)
	)
	->append(
		\StubsGenerator\Finder::create()
			->in(
				[
					'vendor/the-events-calendar/the-events-calendar',
				]
			)
			->files()
			->depth( '== 0' )
	)
	->sortByName();
